id = "blueprint-dark-theme"
name = "Blueprint Dark Theme"
version = "0.1.1"
schema_version = 0.1.0
authors = ["Storm Maxwell"]
description = "Blueprint Dark Theme"
repository = "https://github.com/SM2507/blueprint-dark-theme.git"

themes = ["themes/blueprint-dark-theme.json"]
